# -*- coding: utf-8 -*-
"""Diwali_Sales_Analysis_Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DqjJKKHcckEYrKeeouY3eMH3DcxJRg-x
"""

# Commented out IPython magic to ensure Python compatibility.
# import python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

encoding = 'latin-1'

# import csv file
df=pd.read_csv('/content/Diwali Sales Data.csv',encoding=encoding)
df.shape

df.info()

df.describe()

df.head(10)

df.drop(['Status','unnamed1'],axis=1,inplace=True)     # drop unwanted column

df.info()

pd.isnull(df).sum()             # check null values in our df

df.dropna(inplace=True)        # drop null values

df.shape

# change data types
df['Amount']=df['Amount'].astype('int')

df['Amount'].dtypes

df.columns

# rename column
df.rename(columns={'Marital_Status':'Shadii'})

"""# **Exploratory Data** **Anaysis**

# **Gender**
"""

sns.countplot(x='Gender',data=df)

# plotting a bar chart for Gender and it's count
ax=sns.countplot(x='Gender',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

# plotting a bar chart for gender vs total amount
sales_gen=df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

sns.barplot(x='Gender',y='Amount',data=sales_gen)

"""# **Age** **Group**"""

age=sns.countplot(data=df,x='Age Group')

for bars in age.containers:
  age.bar_label(bars)

age=sns.countplot(data=df,x='Age Group',hue='Gender')               # count calculate

for bars in age.containers:
  age.bar_label(bars)

# total amount vs Age Group
sales_age=df.groupby(['Age Group'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

sns.barplot(x='Age Group',y='Amount',data=sales_age)

"""# **State**"""

# Total number of orders from top 10 state
sales_state=df.groupby(['State'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=sales_state,x='State',y='Orders')

# total amount/sales from top 10 states

sales_state = df.groupby(['State'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'State',y= 'Amount')

"""# **Marital** **Status**"""

ax = sns.countplot(data = df, x = 'Marital_Status')

sns.set(rc={'figure.figsize':(7,5)})
for bars in ax.containers:
    ax.bar_label(bars)

sales_state = df.groupby(['Marital_Status', 'Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data = sales_state, x = 'Marital_Status',y= 'Amount', hue='Gender')

"""# **Occupation**"""

sns.set(rc={'figure.figsize':(20,5)})
ax = sns.countplot(data = df, x = 'Occupation')

for bars in ax.containers:
    ax.bar_label(bars)

sales_state = df.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Occupation',y= 'Amount')

"""# **Product Category**"""

sns.set(rc={'figure.figsize':(20,5)})
ax = sns.countplot(data = df, x = 'Product_Category')

for bars in ax.containers:
    ax.bar_label(bars)

sales_state = df.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_Category',y= 'Amount')

sales_state = df.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_ID',y= 'Orders')

# top 10 most sold products (same thing as above)

fig1, ax1 = plt.subplots(figsize=(12,7))
df.groupby('Product_ID')['Orders'].sum().nlargest(10).sort_values(ascending=False).plot(kind='bar')

"""## **Conclusion:**
Married women age group 26-35 yrs from UP,  Maharastra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food, Clothing and Electronics category
"""